# Generated by Django 3.2.8 on 2021-10-20 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='isim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationDate', models.DateTimeField(auto_now=True, null=True)),
                ('kobilid', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='isim')),
                ('surname', models.CharField(max_length=100, verbose_name='soyisim')),
                ('tc', models.CharField(max_length=100, verbose_name='tc')),
                ('cancerType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vira.cancertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
